version: '2'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - 'docker-postgres:/var/lib/postgresql/data'
  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
volumes:
  docker-postgres: